//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcmoviesassesment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public int Mid { get; set; }
        public string Moviename { get; set; }
        public Nullable<System.DateTime> Dateofrelease { get; set; }
    }
}
